"""artist_pool.py — pure helpers for the Anima artist randomizer.

Provides pool parsing, seeded (reproducible) selection, and lazy loading of
the built-in high-score default pool (``data/artist_pool_default.json``,
generated by ``scripts/fetch_artist_pool.py``). No I/O at import time, so the
selection logic is fully unit-testable without ComfyUI.
"""
from __future__ import annotations

import json
import logging
import random
from pathlib import Path

logger = logging.getLogger(__name__)

# data/artist_pool_default.json — two levels up from python/
_DEFAULT_POOL_PATH = (
    Path(__file__).resolve().parent.parent / "data" / "artist_pool_default.json"
)

# Lazily populated; ``_default_pool_loaded`` guards a single load attempt.
_default_pool_cache: list[str] | None = None
_default_pool_loaded: bool = False


def parse_pool(raw: str) -> list[str]:
    """Split a comma/newline-separated pool string into trimmed unique tags.

    Preconditions:
        - ``raw`` is a str (any other type yields ``[]``).
    Postconditions:
        - Returns tags in first-seen order with case-insensitive de-duplication.
        - Empty / whitespace-only entries are dropped.
    """
    if not isinstance(raw, str) or not raw.strip():
        return []
    out: list[str] = []
    seen: set[str] = set()
    for chunk in raw.replace("\n", ",").split(","):
        tag = chunk.strip()
        if not tag:
            continue
        key = tag.lower()
        if key in seen:
            continue
        seen.add(key)
        out.append(tag)
    return out


def load_default_pool() -> list[str]:
    """Return the built-in high-score artist pool, cached for the process.

    Postconditions:
        - Returns a list of insert-form artist tags (e.g. ``"@sakura shiori"``).
        - Returns ``[]`` (never raises) if the data file is missing or malformed.
    """
    global _default_pool_cache, _default_pool_loaded
    if _default_pool_loaded:
        return _default_pool_cache or []

    _default_pool_loaded = True
    try:
        data = json.loads(_DEFAULT_POOL_PATH.read_text(encoding="utf-8"))
        tags = data.get("tags", []) if isinstance(data, dict) else []
        _default_pool_cache = [
            t.strip() for t in tags if isinstance(t, str) and t.strip()
        ]
        logger.debug(
            "artist default pool loaded: %d tags from %s",
            len(_default_pool_cache),
            _DEFAULT_POOL_PATH,
        )
    except (FileNotFoundError, json.JSONDecodeError, OSError, ValueError) as exc:
        logger.warning(
            "artist_pool_default.json unavailable (%s); default pool empty", exc
        )
        _default_pool_cache = []
    return _default_pool_cache


def pick_artists(pool: list[str], count: int, seed: int) -> list[str]:
    """Deterministically pick up to ``count`` distinct tags from ``pool``.

    Preconditions:
        - ``pool`` is a list of strings.
        - ``count`` and ``seed`` are ints.
    Postconditions:
        - ``count <= 0`` or empty pool -> ``[]``.
        - Returns ``min(count, len(pool))`` distinct tags (no repeats).
        - Selection and order are fully determined by ``seed`` (reproducible:
          the same seed + pool always yields the same result).
    """
    if not pool or count <= 0:
        return []
    n = min(count, len(pool))
    rng = random.Random(seed)
    return rng.sample(pool, n)


def join_artists(tags: list[str], delimiter: str = ", ") -> str:
    """Join ``tags`` with ``delimiter`` (default ``", "``)."""
    return delimiter.join(tags)
